package com.cskaoyan.mapper.schedule;

import com.cskaoyan.domain.schedule.Manufacture;
import com.cskaoyan.domain.schedule.VO.ManufactureVO;

import java.util.HashMap;
import java.util.List;

public interface ManufactureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacture
     *
     * @mbg.generated Fri Aug 31 17:22:24 CST 2018
     */
    int deleteByPrimaryKey(String manufactureSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacture
     *
     * @mbg.generated Fri Aug 31 17:22:24 CST 2018
     */
    int insert(Manufacture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacture
     *
     * @mbg.generated Fri Aug 31 17:22:24 CST 2018
     */
    int insertSelective(Manufacture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacture
     *
     * @mbg.generated Fri Aug 31 17:22:24 CST 2018
     */
    ManufactureVO selectByPrimaryKey(String manufactureSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacture
     *
     * @mbg.generated Fri Aug 31 17:22:24 CST 2018
     */
    int updateByPrimaryKeySelective(Manufacture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacture
     *
     * @mbg.generated Fri Aug 31 17:22:24 CST 2018
     */
    int updateByPrimaryKey(Manufacture record);

    List<ManufactureVO> selectAll();


    List<ManufactureVO> selectByCondition(HashMap map);
}