package com.cskaoyan.mapper.schedule;
import com.cskaoyan.domain.schedule.COrder;
import com.cskaoyan.domain.schedule.VO.COrderVO;

import java.util.HashMap;
import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Aug 31 17:21:55 CST 2018
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Aug 31 17:21:55 CST 2018
     */
    int insert(COrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Aug 31 17:21:55 CST 2018
     */
    int insertSelective(COrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Aug 31 17:21:55 CST 2018
     */
    COrderVO selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Aug 31 17:21:55 CST 2018
     */
    int updateByPrimaryKeySelective(COrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Aug 31 17:21:55 CST 2018
     */
    int updateByPrimaryKey(COrder record);

    List<COrderVO> selectAll();

    List<COrderVO> selectByCondition(HashMap map);
}