package com.cskaoyan.mapper.schedule;

import com.cskaoyan.domain.schedule.Task;
import com.cskaoyan.domain.schedule.VO.TaskVO;

import java.util.HashMap;
import java.util.List;

public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Fri Aug 31 17:22:51 CST 2018
     */
    int deleteByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Fri Aug 31 17:22:51 CST 2018
     */
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Fri Aug 31 17:22:51 CST 2018
     */
    int insertSelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Fri Aug 31 17:22:51 CST 2018
     */
    Task selectByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Fri Aug 31 17:22:51 CST 2018
     */
    int updateByPrimaryKeySelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Fri Aug 31 17:22:51 CST 2018
     */
    int updateByPrimaryKey(Task record);

    List<TaskVO> selectAll();

    List<TaskVO> selectByCondition(HashMap map);
}