package com.cskaoyan.mapper.schedule;

import com.cskaoyan.domain.schedule.VO.WorkVO;
import com.cskaoyan.domain.schedule.Work;

import java.util.HashMap;
import java.util.List;

public interface WorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Fri Aug 31 17:23:10 CST 2018
     */
    int deleteByPrimaryKey(String workId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Fri Aug 31 17:23:10 CST 2018
     */
    int insert(Work record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Fri Aug 31 17:23:10 CST 2018
     */
    int insertSelective(Work record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Fri Aug 31 17:23:10 CST 2018
     */
    Work selectByPrimaryKey(String workId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Fri Aug 31 17:23:10 CST 2018
     */
    int updateByPrimaryKeySelective(Work record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Fri Aug 31 17:23:10 CST 2018
     */
    int updateByPrimaryKey(Work record);

    List<WorkVO> selectAll();

    List<WorkVO> selectByCondition(HashMap map);




}